name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate iOS project and install pods
        run: npx expo prebuild --platform ios

      - name: Build iOS App (Unsigned)
        run: |
          xcodebuild -workspace ios/ChessTimeIOS.xcworkspace \
                     -scheme ChessTimeIOS \
                     -configuration Release \
                     -sdk iphoneos \
                     -derivedDataPath build \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     PROVISIONING_PROFILE_REQUIRED=NO

      - name: Package IPA
        run: |
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/ChessTimeIOS.app Payload/
          zip -qq -r -9 ChessTimeIOS.ipa Payload

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ChessTimeIOS.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"

